
version: '3.2'
services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./log:/var/log
      - ./public:/app/public

  mongodb:
    image: mongo
    container_name: mongo2
    restart: always
    ports:
        - "27020:27017"
    command: --storageEngine wiredTiger
 